from __future__ import annotations

from enum import StrEnum


class MemoryEventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    EVIDENCE_CAPTURED = "EVIDENCE_CAPTURED"
    TRIAGE_COMPLETED = "TRIAGE_COMPLETED"
    CAPABILITY_LOOKUP_COMPLETED = "CAPABILITY_LOOKUP_COMPLETED"
    HUMAN_APPROVAL_COMPLETED = "HUMAN_APPROVAL_COMPLETED"
    RPA_WRITEBACK_COMPLETED = "RPA_WRITEBACK_COMPLETED"
    VALIDATION_COMPLETED = "VALIDATION_COMPLETED"
    API_EXECUTION_COMPLETED = "API_EXECUTION_COMPLETED"
    CAPABILITY_GAP_RECORDED = "CAPABILITY_GAP_RECORDED"
    CAPABILITY_REGISTERED = "CAPABILITY_REGISTERED"
    READINESS_ASSESSED = "READINESS_ASSESSED"
